### ISSUE TITLE
[develop] Core dump after setting mail server and sending a transaction

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#992]
This is newly initialized blockchain...  

```
default (unlocked) >>> transfer 500 XTS delegate0 delegate1
TIMESTAMP           BLOCK     FROM                TO                  AMOUNT                  MEMO                                        FEE                 ID      
======================================================================================================================================================================
2014-11-15T18:54:40 PENDING   delegate0           delegate1           500.00000 XTS                                                       0.50000 XTS         f2d0bcbb
Email 1722361f95ca019c6db4d82b0f291babf4da2a96: Timeout when transmitting
default (unlocked) >>> wallet_account_./client.sh: line 61:  8134 Segmentation fault      (core dumped) ${GDB-} "${BTS_BUILD}/programs/client/bitshares_client" --data-dir "$testnet_datadir" --genesis-config "$BTS_JS/testnet/config/genesis.json" --server --httpport=$HTTP_PORT --rpcport=$RPC_PORT --rpcuser=test --rpcpassword=test --upnp=false --connect-to=$P2P_HOST --disable-default-peers
```
Not sure if it is directly related to the mail server or not, there is value in seeing how it crashed though.  I restarted the client in gdb and it crashed right away so I could get the backtrace:
 ```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000b23df8 in bts::wallet::detail::wallet_impl::scan_transaction_experimental (this=0x20f7700, eval_state=..., account_keys=..., account_balances=..., account_names=..., 
    record=..., store_record=true) at /home/jcalfee/b/develop/libraries/wallet/transaction_ledger_experimental.cpp:113
113	{ try {
(gdb) bt
#0  0x0000000000b23df8 in bts::wallet::detail::wallet_impl::scan_transaction_experimental (this=0x20f7700, eval_state=..., account_keys=..., account_balances=..., account_names=..., 
    record=..., store_record=true) at /home/jcalfee/b/develop/libraries/wallet/transaction_ledger_experimental.cpp:113
#1  0x0000000000b2cd6a in bts::wallet::detail::wallet_impl::__lambda16::operator() (__closure=__closure@entry=0x7fffc66d2880)
    at /home/jcalfee/b/develop/libraries/wallet/transaction_ledger_experimental.cpp:472
#2  0x0000000000b240f1 in bts::wallet::detail::wallet_impl::scan_transaction_experimental (this=this@entry=0x20f7700, eval_state=..., account_keys=..., account_balances=..., 
    account_names=..., record=..., store_record=store_record@entry=true) at /home/jcalfee/b/develop/libraries/wallet/transaction_ledger_experimental.cpp:476
#3  0x0000000000b27751 in bts::wallet::detail::wallet_impl::scan_transaction_experimental (this=this@entry=0x20f7700, eval_state=..., block_num=block_num@entry=15, timestamp=..., 
    account_keys=..., account_balances=..., account_names=..., overwrite_existing=overwrite_existing@entry=true)
    at /home/jcalfee/b/develop/libraries/wallet/transaction_ledger_experimental.cpp:102
#4  0x0000000000b281c2 in bts::wallet::detail::wallet_impl::scan_block_experimental (this=this@entry=0x20f7700, block_num=block_num@entry=15, account_keys=..., account_balances=..., 
    account_names=...) at /home/jcalfee/b/develop/libraries/wallet/transaction_ledger_experimental.cpp:51
#5  0x0000000000bd618d in bts::wallet::detail::wallet_impl::scan_chain_task (this=0x20f7700, start=14, end=<optimized out>, fast_scan=false)
    at /home/jcalfee/b/develop/libraries/wallet/wallet.cpp:241
#6  0x0000000000bd75ad in operator() (__closure=<optimized out>) at /home/jcalfee/b/develop/libraries/wallet/wallet.cpp:1465
#7  fc::detail::void_functor_run<bts::wallet::wallet::scan_chain(uint32_t, uint32_t, bool)::__lambda5>::run(void *, void *) (functor=<optimized out>, prom=0x21e1740)
    at /home/jcalfee/b/develop/libraries/fc/include/fc/thread/task.hpp:83
#8  0x00000000008f3af3 in fc::task_base::run_impl (this=this@entry=0x21e1760) at /home/jcalfee/b/develop/libraries/fc/src/thread/task.cpp:43
#9  0x00000000008f41a5 in fc::task_base::run (this=this@entry=0x21e1760) at /home/jcalfee/b/develop/libraries/fc/src/thread/task.cpp:32
#10 0x00000000008f214e in run_next_task (this=0x1fdf1a0) at /home/jcalfee/b/develop/libraries/fc/src/thread/thread_d.hpp:498
#11 fc::thread_d::process_tasks (this=this@entry=0x1fdf1a0) at /home/jcalfee/b/develop/libraries/fc/src/thread/thread_d.hpp:547
#12 0x00000000008f23c1 in fc::thread_d::start_process_tasks (my=33419680) at /home/jcalfee/b/develop/libraries/fc/src/thread/thread_d.hpp:475
#13 0x000000000125d69e in make_fcontext ()
#14 0x0000000001fdf1a0 in ?? ()
#15 0x000000000222f750 in ?? ()
#16 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by vikramrajkumar** [comment]
The experimental scanner has been re-disabled for a while now.
